# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 20:06
from __future__ import unicode_literals

import App.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(verbose_name='Street Number')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('month', models.CharField(max_length=200, verbose_name='Month')),
                ('code', models.CharField(max_length=200, verbose_name='Code')),
                ('collaborator', models.ManyToManyField(to='App.Collaborator')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('code', models.CharField(max_length=200, verbose_name='Code')),
                ('content', models.CharField(max_length=200, verbose_name='Content')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='LabelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Entry Date')),
                ('event', models.CharField(max_length=200, verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Order Date')),
                ('order_number', models.IntegerField(verbose_name='Order Number')),
                ('originated_From', models.CharField(max_length=200, verbose_name='Originated From')),
                ('order_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Order Status')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern_Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200, verbose_name='SKU')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('image_path', models.FileField(upload_to=App.models.get_upload_file_name)),
                ('tech_pack_path', models.FileField(upload_to=App.models.get_upload_file_name)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Fabric_Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Fabric')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Notion_Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Notion')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Class_Type')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, verbose_name='Size')),
                ('code', models.CharField(max_length=200, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('code', models.CharField(max_length=200, verbose_name='Code')),
                ('pattern_pieces', models.ManyToManyField(to='App.Pattern_Piece')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('code', models.CharField(max_length=200, verbose_name='Code')),
                ('pattern_pieces', models.ManyToManyField(to='App.Pattern_Piece')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(to='App.Product_Fabric_Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_tag',
            field=models.ManyToManyField(to='App.LabelTag'),
        ),
        migrations.AddField(
            model_name='product',
            name='notions',
            field=models.ManyToManyField(to='App.Product_Notion_Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Style'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Variation'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='App.Product_Quantity'),
        ),
        migrations.AddField(
            model_name='collection',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Season'),
        ),
    ]
