# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_LabelTag_Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Label/Tag on Product',
                'verbose_name_plural': 'Label/Tags on Product',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='class_type',
            options={'verbose_name': 'Class Type', 'verbose_name_plural': 'Class Types'},
        ),
        migrations.AlterModelOptions(
            name='labeltag',
            options={'verbose_name': 'Label/Tag', 'verbose_name_plural': 'Labels/Tags'},
        ),
        migrations.AlterModelOptions(
            name='log_entry',
            options={'verbose_name': 'Log Entry', 'verbose_name_plural': 'Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='pattern_piece',
            options={'verbose_name': 'Pattern Piece', 'verbose_name_plural': 'Pattern Pieces'},
        ),
        migrations.AlterModelOptions(
            name='product_fabric_quantity',
            options={'verbose_name': 'Fabric on Product', 'verbose_name_plural': 'Fabrics on Product'},
        ),
        migrations.AlterModelOptions(
            name='product_notion_quantity',
            options={'verbose_name': 'Notion on Product', 'verbose_name_plural': 'Notions on Product'},
        ),
        migrations.AlterModelOptions(
            name='product_quantity',
            options={'verbose_name': 'Product on Order', 'verbose_name_plural': 'Products on Order'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='labeltag',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='notion',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label_tag',
            field=models.ManyToManyField(to='App.Product_LabelTag_Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product_fabric_quantity',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product_notion_quantity',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product_quantity',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product_labeltag_quantity',
            name='labeltag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.LabelTag'),
        ),
    ]
