# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fabric',
            new_name='fabrics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='notion',
        ),
        migrations.AddField(
            model_name='product',
            name='notions',
            field=models.ManyToManyField(blank=True, to='App.Product_Notion_Quantity'),
        ),
    ]
