# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20161116_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notions',
            field=models.ManyToManyField(to='App.Product_Notion_Quantity'),
        ),
    ]
