# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=200, verbose_name='Size'),
        ),
    ]
