# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20161117_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_Entry',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
    ]
