# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20161111_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=100, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='month',
            field=models.CharField(max_length=200, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='labeltag',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='labeltag',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='labeltag',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='labeltag',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='log_entry',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='log_entry',
            name='event',
            field=models.CharField(max_length=200, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='notion',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notion',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='notion',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='notion',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='originated_From',
            field=models.CharField(max_length=200, verbose_name='Originated From'),
        ),
        migrations.AlterField(
            model_name='pattern_piece',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=200, verbose_name='Image Path'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=200, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tech_pack_path',
            field=models.CharField(max_length=200, verbose_name='Tech Pack Path'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='style',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='style',
            name='pattern_pieces',
            field=models.CharField(max_length=200, verbose_name='Pattern Pieces'),
        ),
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='pattern_pieces',
            field=models.CharField(max_length=200, verbose_name='Pattern Pieces'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
