# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20161116_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
    ]
