# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20161114_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator_collection',
            name='collaborator_id',
        ),
        migrations.RemoveField(
            model_name='collaborator_collection',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='fabric_product',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='fabric_product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='labeltag_product',
            name='labelTag_id',
        ),
        migrations.RemoveField(
            model_name='labeltag_product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='notion_product',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='notion_product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_sku',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_sku',
            name='product_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='collaborator',
            field=models.ManyToManyField(to='App.Collaborator'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='App.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ManyToManyField(to='App.Fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_tag',
            field=models.ManyToManyField(to='App.LabelTag'),
        ),
        migrations.AddField(
            model_name='product',
            name='notion',
            field=models.ManyToManyField(to='App.Notion'),
        ),
        migrations.DeleteModel(
            name='Collaborator_Collection',
        ),
        migrations.DeleteModel(
            name='Fabric_Product',
        ),
        migrations.DeleteModel(
            name='LabelTag_Product',
        ),
        migrations.DeleteModel(
            name='Notion_Product',
        ),
        migrations.DeleteModel(
            name='Order_Sku',
        ),
    ]
