# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20161114_1410'),
        ('App', '0006_auto_20161114_1346'),
    ]

    operations = [
    ]
