# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20161114_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern_piece',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
